// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wqqpazsaxjfqvvxtzrkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndxcXBhenNheGpmcXZ2eHR6cmtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MDk1OTEsImV4cCI6MjA2OTE4NTU5MX0.UA0dhDyBijDwGTXgRMd2YA-cjlil-6vu_6mFHbLTEXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});